#!/usr/bin/env python3
# Generates base/screens/weather2.yaml (alternative "Weather 2" screen, base id 10).
#   python scripts/gen_weather2.py
#
# Sits next to weather.yaml and REUSES its data (g_wx_* globals, HA sensors, icons_wx font), so
# weather.yaml must also be included. Modern look: fixed partly-cloudy palette, big colour-coded
# temperature, ANIMATED condition icons (animimg frame loops), and a glow that slides along the rim
# to the selected day. Every HA condition maps to one of 7 animated icons (unknown -> cloud).
# Animated frames live in assets/sprites/weather/<key>0..7.png (generated separately with Pillow).
import os

ICONS = ["sun", "partly", "moon", "cloud", "rain", "storm", "snow"]  # 8 frames each
NF = 8
DUR = "1400ms"   # animation cycle (gentle)
BASE = "https://raw.githubusercontent.com/MichalZaniewicz/esphome-guition-jc3636k718c-va/beta/assets/sprites/weather/"

# fixed partly-cloudy palette
BG = "0x1C2838"; ICON_TINT = "0xCAD6E8"; GLOW = "0xCAD6E8"; HUD = "0xFFFFFF"
RIM = "0xDCE6F2"; ACCENT = "0x9AA6B2"; CONDC = "0xCFE0F2"; PAGE = "0x0B1020"


def image_block():
    out = []
    for k in ICONS:
        for i in range(NF):
            out.append(
f"""  - id: img_wx_{k}{i}
    file: "{BASE}{k}{i}.png"
    type: RGB565
    transparency: alpha_channel""")
    return "\n".join(out)


def animimg_widgets():
    out = []
    for k in ICONS:
        src = ", ".join(f"img_wx_{k}{i}" for i in range(NF))
        out.append(
            f"        - animimg: {{ id: wx2_a_{k}, align: CENTER, x: 0, y: -52, duration: {DUR}, "
            f"repeat_count: 65535, auto_start: false, hidden: true, src: [ {src} ] }}")
    return "\n".join(out)


def dispatch_stop_hide():
    out = [f"            - lvgl.animimg.stop: wx2_a_{k}" for k in ICONS]
    out += [f"            - lvgl.widget.hide: wx2_a_{k}" for k in ICONS]
    return "\n".join(out)


def dispatch_show():
    return "\n".join(
        f"            - if: {{ condition: {{ lambda: 'return id(g_wx2_ikey) == \"{k}\";' }}, "
        f"then: [ lvgl.widget.show: wx2_a_{k}, lvgl.animimg.start: wx2_a_{k} ] }}"
        for k in ICONS)


def rim_updates():
    out = []
    for i in range(7):
        out.append(
            f"      - lvgl.widget.update: {{ id: wx2_d{i}, hidden: !lambda 'return {i} >= id(g_wx_n);', "
            f"x: !lambda 'int n=id(g_wx_n); if(n<1)n=1; return (int) lroundf(140.0f * sinf({i} * 6.2831853f / n));', "
            f"y: !lambda 'int n=id(g_wx_n); if(n<1)n=1; return (int) lroundf(-140.0f * cosf({i} * 6.2831853f / n));' }}")
        out.append(
            f"      - lvgl.label.update:  {{ id: wx2_d{i}, text: !lambda 'return id(g_wx_n) > {i} ? id(g_wx_icon)[{i}] : std::string(\"\");' }}")
    return "\n".join(out)


def rim_widgets():
    return "\n".join(
        f"        - label: {{ id: wx2_d{i}, align: CENTER, x: 0, y: 0, text: \"\", text_font: icons_wx, text_color: {RIM}, hidden: true }}"
        for i in range(7))


YAML = f"""# Weather 2 - ALTERNATIVE weather screen (base id 10). GENERATED by scripts/gen_weather2.py.
# Sits next to weather.yaml and REUSES its data (g_wx_* globals, HA sensors, icons_wx font) - so
# weather.yaml must also be included. Fixed partly-cloudy palette, colour-coded temperature,
# animated condition icons (animimg), and a glow that slides along the rim to the selected day.

esphome:
  on_boot:
    - priority: 654
      then:
        - lambda: 'id(g_present)[10] = true;'

globals:
  - id: g_wx2_sel        # selected day's condition
    type: std::string
    restore_value: no
  - id: g_wx2_tc         # selected day's temp in C (colour-coding)
    type: int
    restore_value: no
    initial_value: '-127'
  - id: g_wx2_lastcond   # last condition shown (so the animimg only switches/starts on change)
    type: std::string
    restore_value: no
  - id: g_wx2_ikey       # which animated icon key is active (sun/partly/moon/cloud/rain/storm/snow)
    type: std::string
    restore_value: no
  - id: g_wx2_gpos       # current glow position (fractional day index) - slides toward g_wx_day
    type: float
    restore_value: no
    initial_value: '0.0'

image:
{image_block()}

script:
  - id: wx2_render
    then:
      - lambda: |-
          int d = id(g_wx_day);
          bool has = (id(g_wx_n) > 0 && d < id(g_wx_n));
          id(g_wx2_sel) = has ? id(g_wx_cond)[d] : id(g_wx_state_cur);
          id(g_wx2_tc)  = has ? id(g_wx_hi)[d] : id(g_wx_now);
      - lvgl.label.update:
          id: wx2_day
          text: !lambda |-
            int d = id(g_wx_day);
            if (id(g_wx_n) <= 0 || d >= id(g_wx_n)) return std::string("TODAY");
            std::string s = id(g_wx_name)[d];
            if (s == "Mon") return std::string("MONDAY");
            if (s == "Tue") return std::string("TUESDAY");
            if (s == "Wed") return std::string("WEDNESDAY");
            if (s == "Thu") return std::string("THURSDAY");
            if (s == "Fri") return std::string("FRIDAY");
            if (s == "Sat") return std::string("SATURDAY");
            if (s == "Sun") return std::string("SUNDAY");
            return s;
      - lvgl.label.update:
          id: wx2_temp
          text: !lambda |-
            int d = id(g_wx_day);
            bool f = id(g_wx_fahrenheit);
            char u = f ? 'F' : 'C';
            if (id(g_wx_n) <= 0 || d >= id(g_wx_n)) {{
              if (id(g_wx_now) > -100) {{ int n = id(g_wx_now); if (f) n = n*9/5+32; char b[12]; snprintf(b,sizeof(b),"%d°%c",n,u); return std::string(b); }}
              return std::string("--");
            }}
            int hi = id(g_wx_hi)[d], lo = id(g_wx_lo)[d];
            if (f) {{ hi = hi*9/5+32; lo = lo*9/5+32; }}
            char b[24]; snprintf(b,sizeof(b),"%d° / %d°",hi,lo); return std::string(b);
      - lvgl.label.update:
          id: wx2_cond
          text: !lambda |-
            if (id(g_wx_n) <= 0) return std::string("Add the HA forecast helper");
            std::string s = id(g_wx2_sel);
            if (s == "sunny") return std::string("Sunny");
            if (s == "clear-night") return std::string("Clear");
            if (s == "partlycloudy") return std::string("Partly Cloudy");
            if (s == "cloudy") return std::string("Cloudy");
            if (s == "fog") return std::string("Fog");
            if (s == "rainy") return std::string("Rainy");
            if (s == "pouring") return std::string("Heavy Rain");
            if (s == "lightning" || s == "lightning-rainy") return std::string("Storm");
            if (s == "snowy" || s == "snowy-rainy") return std::string("Snow");
            if (s == "hail") return std::string("Hail");
            if (s == "windy" || s == "windy-variant") return std::string("Windy");
            if (s == "exceptional") return std::string("Severe");
            return s;
      # animated hero icon: pick a key per condition; switch/start only when it changes
      - if:
          condition: {{ lambda: 'return id(g_wx2_sel) != id(g_wx2_lastcond);' }}
          then:
            - lambda: |-
                id(g_wx2_lastcond) = id(g_wx2_sel);
                std::string s = id(g_wx2_sel), k;
                if (s == "sunny") k = "sun";
                else if (s == "clear-night") k = "moon";
                else if (s == "partlycloudy") k = "partly";
                else if (s == "rainy" || s == "pouring") k = "rain";
                else if (s == "lightning" || s == "lightning-rainy") k = "storm";
                else if (s == "snowy" || s == "snowy-rainy" || s == "hail") k = "snow";
                else k = "cloud";   // cloudy / fog / windy / exceptional / unknown -> cloud
                id(g_wx2_ikey) = k;
{dispatch_stop_hide()}
{dispatch_show()}
      - lvgl.widget.update: {{ id: wx2_glow, hidden: !lambda 'return id(g_wx_n) <= 0;' }}
      # rim day icons
{rim_updates()}
      # temperature colour by value (C)
      - lvgl.label.update: {{ id: wx2_temp, text_color: 0xFFFFFF }}
      - if: {{ condition: {{ lambda: 'return id(g_wx2_tc) > -100 && id(g_wx2_tc) <= 0;' }},  then: [ lvgl.label.update: {{ id: wx2_temp, text_color: 0x7FB2FF }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx2_tc) > 0 && id(g_wx2_tc) < 10;' }},     then: [ lvgl.label.update: {{ id: wx2_temp, text_color: 0x6FD0E8 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx2_tc) >= 10 && id(g_wx2_tc) < 18;' }},   then: [ lvgl.label.update: {{ id: wx2_temp, text_color: 0x7FE6B0 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx2_tc) >= 18 && id(g_wx2_tc) < 25;' }},   then: [ lvgl.label.update: {{ id: wx2_temp, text_color: 0xFFD061 }} ] }}
      - if: {{ condition: {{ lambda: 'return id(g_wx2_tc) >= 25;' }},                        then: [ lvgl.label.update: {{ id: wx2_temp, text_color: 0xFF7A4D }} ] }}

interval:
  - interval: 50ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_nav_req) && id(g_base)==10;' }}
          then:
            - lambda: 'id(g_nav_req) = false; id(g_knob_capture) = true; id(g_wx_day) = 0; id(g_wx2_gpos) = 0.0f; id(g_wx2_lastcond) = "";'
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==0;' }}, then: [lvgl.page.show: {{ id: page_weather2, animation: move_left,   time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==1;' }}, then: [lvgl.page.show: {{ id: page_weather2, animation: move_right,  time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==2;' }}, then: [lvgl.page.show: {{ id: page_weather2, animation: move_top,    time: 250ms }}] }}
            - if: {{ condition: {{ lambda: 'return id(g_nav_anim)==3;' }}, then: [lvgl.page.show: {{ id: page_weather2, animation: move_bottom, time: 250ms }}] }}
            - script.execute: wx2_render
  - interval: 120ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_base)==10 && id(g_knob_delta) != 0;' }}
          then:
            - lambda: |-
                id(g_wx_day) += id(g_knob_delta); id(g_knob_delta) = 0;
                int mx = (id(g_wx_n) > 0) ? id(g_wx_n) - 1 : 0;
                if (id(g_wx_day) < 0) id(g_wx_day) = 0;
                if (id(g_wx_day) > mx) id(g_wx_day) = mx;
            - script.execute: wx2_render
  # slide the glow toward the selected day (30ms)
  - interval: 30ms
    then:
      - if:
          condition: {{ lambda: 'return id(g_base)==10;' }}
          then:
            - lambda: |-
                int n = id(g_wx_n); if (n < 1) n = 1;
                float p = id(g_wx2_gpos), tgt = (float) id(g_wx_day);
                p += (tgt - p) * 0.35f;
                if (fabsf(tgt - p) < 0.02f) p = tgt;
                id(g_wx2_gpos) = p;
                float rx = 140.0f * sinf(p * 6.2831853f / n);
                float ry = -140.0f * cosf(p * 6.2831853f / n);
                lv_obj_set_pos(id(wx2_glow), 180 + (int) lroundf(rx) - 28, 180 + (int) lroundf(ry) - 28);
  - interval: 1s
    then:
      - if:
          condition: {{ lambda: 'return id(g_base)==10;' }}
          then: [ script.execute: wx2_render ]

lvgl:
  pages:
    - id: page_weather2
      bg_color: {PAGE}
      widgets:
        - obj: {{ id: wx2_bg, align: CENTER, x: 0, y: 0, width: 360, height: 360, radius: 0, bg_color: {BG}, bg_opa: COVER, border_width: 0 }}
        # soft glow behind the selected day (no align - slid via lv_obj_set_pos)
        - obj: {{ id: wx2_glow, x: 152, y: 12, width: 56, height: 56, radius: 28, bg_color: {GLOW}, bg_opa: 30%, border_width: 0, hidden: true }}
{rim_widgets()}
        # animated hero icons (one shown per condition)
{animimg_widgets()}
        - label: {{ id: wx2_day, align: CENTER, x: 0, y: -10, text: "", text_font: font_artist, text_color: {ACCENT} }}
        - label: {{ id: wx2_temp, align: CENTER, x: 0, y: 24, text: "--", text_font: montserrat_34, text_color: {HUD} }}
        - label: {{ id: wx2_cond, align: CENTER, x: 0, y: 62, text: "", text_font: font_med, text_color: {CONDC} }}
"""

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.normpath(os.path.join(here, "..", "base", "screens", "weather2.yaml"))
with open(out, "w", encoding="utf-8", newline="\n") as f:
    f.write(YAML)
print("wrote", out, "(", len(YAML), "bytes )")
